set(MINGW_ENABLE_POSIX ON CACHE STRING "Enable MinGW POSIX subsystem")

set(MINGW_COMPILER_SUFIX )

if(MINGW_ENABLE_POSIX)
    set(MINGW_COMPILER_SUFIX -posix)
endif()

set(CMAKE_SYSTEM_NAME Windows)

set(CMAKE_C_COMPILER ${MINGW_TOOLCHAIN_PREFIX}-gcc${MINGW_COMPILER_SUFIX})
set(CMAKE_CXX_COMPILER ${MINGW_TOOLCHAIN_PREFIX}-g++${MINGW_COMPILER_SUFIX})
set(CMAKE_RC_COMPILER ${MINGW_TOOLCHAIN_PREFIX}-windres)

set(CMAKE_SHARED_LIBRARY_PREFIX_C "")
set(CMAKE_SHARED_LIBRARY_PREFIX_CXX "")

set(CMAKE_FIND_ROOT_PATH /usr/${MINGW_TOOLCHAIN_PREFIX})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

add_link_options(-static)
