#pragma once
#include "default.h"
#include "variable.h"

#define SIMPLEJS_BYTECODE_HEADER_SIZE 4
#define SIMPLEJS_BYTECODE_VERSION 1

#define SIMPLEJS_BYTECODE_BASE_INSTRUCTION_SIZE 4
#define SIMPLEJS_BYTECODE_EXTENDED_INSTRUCTION_SIZE 6

typedef enum
{
    SIMPLEJS_BYTECODE_OPCODE_MOV_VAR,

    SIMPLEJS_BYTECODE_OPCODE_ADD_STACK,
    SIMPLEJS_BYTECODE_OPCODE_ADD_STACK_VAR_SIZE,

    SIMPLEJS_BYTECODE_OPCODE_SAVE_CTX,
    SIMPLEJS_BYTECODE_OPCODE_RESTORE_CTX,

    SIMPLEJS_BYTECODE_OPCODE_INIT_LOC_OFFSET,
    SIMPLEJS_BYTECODE_OPCODE_INIT_ARG_OFFSET,
    SIMPLEJS_BYTECODE_OPCODE_SAVE_ARG_OFFSET,

    SIMPLEJS_BYTECODE_OPCODE_ALLOC_ARGS,
    SIMPLEJS_BYTECODE_OPCODE_FREE_ARGS,

    SIMPLEJS_BYTECODE_OPCODE_INIT_LOC_VAR,
    SIMPLEJS_BYTECODE_OPCODE_FREE_LOC_VAR,

    SIMPLEJS_BYTECODE_OPCODE_GET_VAR_PROP,
    SIMPLEJS_BYTECODE_OPCODE_SET_VAR_PROP,

    SIMPLEJS_BYTECODE_OPCODE_GET_GLOBAL_VAR,

    SIMPLEJS_BYTECODE_OPCODE_GET_LOC_VAR,
    SIMPLEJS_BYTECODE_OPCODE_SET_LOC_VAR,

    SIMPLEJS_BYTECODE_OPCODE_GET_ARG_VAR,
    SIMPLEJS_BYTECODE_OPCODE_SET_ARG_VAR,

    SIMPLEJS_BYTECODE_OPCODE_SET_VAR_NUMBER,
    SIMPLEJS_BYTECODE_OPCODE_SET_VAR_NATIVE_FUNCTION,
    SIMPLEJS_BYTECODE_OPCODE_SET_VAR_FAST_STRING,

    SIMPLEJS_BYTECODE_OPCODE_CALL,
    SIMPLEJS_BYTECODE_OPCODE_RETURN,

    SIMPLEJS_BYTECODE_OPCODE_JMP,
    SIMPLEJS_BYTECODE_OPCODE_JMP_IF_ZERO,

    SIMPLEJS_BYTECODE_OPCODE_EXIT,

    SIMPLEJS_BYTECODE_OPCODE_INC_VAR,
    SIMPLEJS_BYTECODE_OPCODE_DEC_VAR,

    SIMPLEJS_BYTECODE_OPCODE_EQUAL_VAR,
    SIMPLEJS_BYTECODE_OPCODE_GREATER_VAR,
    SIMPLEJS_BYTECODE_OPCODE_BELOW_VAR,

    SIMPLEJS_BYTECODE_OPCODE_ADD_VAR,
    SIMPLEJS_BYTECODE_OPCODE_SUB_VAR,
    SIMPLEJS_BYTECODE_OPCODE_MUL_VAR,
    SIMPLEJS_BYTECODE_OPCODE_DIV_VAR,
    SIMPLEJS_BYTECODE_OPCODE_MOD_VAR,

    SIMPLEJS_BYTECODE_OPCODE_END = 0x7F,
} simplejs_bytecode_opcode_t;

#pragma pack(push, 1)

typedef struct simplejs_bytecode_header
{
    uint8_t size_low;
    uint8_t size_high;

    uint8_t version_low;
    uint8_t version_high;
} simplejs_bytecode_header_t;

#pragma pack(pop)

#pragma pack(push, 1)

typedef struct simplejs_bytecode_instruction
{
    uint8_t opcode : 7;
    uint8_t extended_opcode : 1;

    uint8_t reg_1 : 4;
    uint8_t reg_2 : 4;

    union {
        uint32_t imm;
        int32_t imm_signed;
    };
} simplejs_bytecode_instruction_t;

#pragma pack(pop)

typedef enum
{
    SIMPLEJS_BYTECODE_VARIABLE_FUNC_RETURN,

    SIMPLEJS_BYTECODE_VARIABLE_ASSIGN_A,
    SIMPLEJS_BYTECODE_VARIABLE_ASSIGN_B,
    SIMPLEJS_BYTECODE_VARIABLE_PROPERTY,
    SIMPLEJS_BYTECODE_VARIABLE_GLOBAL,

    SIMPLEJS_BYTECODE_VARIABLE_RESULT,
    SIMPLEJS_BYTECODE_VARIABLE_OP_A,
    SIMPLEJS_BYTECODE_VARIABLE_OP_B,

    SIMPLEJS_BYTECODE_VARIABLE_FUNCTION,
    SIMPLEJS_BYTECODE_VARIABLE_ARGUMENT,
} simplejs_bytecode_variable_t;

void simplejs_bytecode_encode(uint8_t *buffer, simplejs_bytecode_instruction_t *instruction, uint8_t *instruction_size);
void simplejs_bytecode_decode(simplejs_bytecode_instruction_t *instruction, uint8_t *buffer, uint8_t *instruction_size);
