#include <lib/status.h>

const pchar SIMPLEJS_API simplejs_get_status_string(simplejs_status_t status)
{
    switch (status)
    {
        CASE_TO_STRING(SIMPLEJS_STATUS_SUCCESS);
        CASE_TO_STRING(SIMPLEJS_STATUS_UNSUCCESSFUL);
        CASE_TO_STRING(SIMPLEJS_STATUS_STACK_OUT_OF_BOUNDS);
        CASE_TO_STRING(SIMPLEJS_STATUS_MEMORY_OUT_OF_BOUNDS);
        CASE_TO_STRING(SIMPLEJS_STATUS_PROGRAM_EXITED);
        CASE_TO_STRING(SIMPLEJS_STATUS_PROGRAM_CRASHED);
        CASE_TO_STRING(SIMPLEJS_STATUS_NOT_IMPLEMENTED);
        CASE_TO_STRING(SIMPLEJS_STATUS_OBJECT_NAME_DOES_NOT_EXIST);
        CASE_TO_STRING(SIMPLEJS_STATUS_ALLOCATION_ERROR);
        CASE_TO_STRING(SIMPLEJS_STATUS_ENCODING_ERROR);
        CASE_TO_STRING(SIMPLEJS_STATUS_INVALID_TOKEN);
        CASE_TO_STRING(SIMPLEJS_STATUS_INVALID_OPCODE);
        CASE_TO_STRING(SIMPLEJS_STATUS_INVALID_PARAMETER);
    }

    return "Unknown";
}
